### ISSUE TITLE
As a tester, I'd like a webview test that asserts Texts and pictures of the book appear when scrolling down

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#100]
1. Go to test environment

2. Click on any books

3. Scroll down
The content with text and pictures is displayed.

**Comment by Dantemss** [comment]
https://github.com/openstax/cnx-automation/pull/118

Testing only that the content is there. Testing that the content appears as we scroll seems out of scope to me (it sounds more like a browser scrolling functionality test)
