### ISSUE TITLE
tox blows up on relative import of the test data file

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#11]
This is probably due to the working directory of wherever the pytest command is being executed. The best bet is probably to create a variable in the `conftest.py` file that figures out it's own filepath and the relation of the data directory to that. 

I believe something like this may do the trick:

`DATA_DIR = os.path.join(os.path.realpath(os.path.dirname(__file__)), 'data')`

**Comment by kerwinso** [comment]
Addressed by #12.
