### ISSUE TITLE
AAT, I'd like a webview test that asserts robots.txt on staging should have 'disallow' content

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#160]
# CASE NUM: C181347

## User story

```
AAT, I'd like a webview test that asserts robots.txt on staging should have 'disallow' content
```

## Preconditions

```

```

## Steps

```
Go to http://staging.cnx.org/robots.txt . The content should match the following:

```
User-agent: *
Disallow: /

User-agent: ScoutJet
Crawl-delay: 10
Disallow: /

User-agent: Baiduspider
Crawl-delay: 10
Disallow: /

User-agent: BecomeBot
Crawl-delay: 20
Disallow: /

User-agent: Slurp
Crawl-delay: 10
Disallow: /
```
```

## Expected Result

```

```

**Comment by Dantemss** [comment]
QA has different content, so I had to special-case staging.

https://github.com/openstax/cnx-automation/pull/207
