### ISSUE TITLE
AAT, I'd like a webview test that asserts Unicode in URL should not cause page to "flicker"

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#167]
# CASE NUM: C195074

## User story

```
AAT, I'd like a webview test that asserts Unicode in URL should not cause page to "flicker"
```

## Preconditions

```

```

## Steps

1. Go to https://staging.cnx.org/contents/e7a016d3-91fc-4ba0-9e05-a33e986f3d94@10.36:68/Conceptos-de-Biolog%C3%ADa
1. If the page appears to be reloading over and over without the content loading, this is a bug.

## Expected Result

```

```

**Comment by Dantemss** [comment]
@kerwinso did the page load forever when there was a bug or did it load eventually? (is it enough for the automation test to simply test that the page finishes loading?)

**Comment by Dantemss** [comment]
Apparently the page got stuck in a load loop (it would load and then reload forever). I think the best we can do here without being able to reproduce it is to add the URL to our tests and hope they fail if the page gets stuck in a load loop.

**Comment by Dantemss** [comment]
The page linked in this issue no longer has the same slug, so I doubt it would even trigger the original bug. I'll replace it with a page that should get a slug with unicode characters (except webview seems to currently remove the unicode characters from the slug)
