### ISSUE TITLE
AAT, I'd like a webview test that asserts Top nav links should have new ids in HTML

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#169]
# CASE NUM: C195236

## User story

```
AAT, I'd like a webview test that asserts Top nav links should have new ids in HTML
```

## Preconditions

```

```

## Steps

1. go to front page of testing environment
1. in your browser, inspect the element classes for the top navigation links

## Expected Result

- Search link should have `id="nav-browse"`
- About link should have `id="nav-about"`
- Give link should have `id="nav-donate"`

**Comment by Dantemss** [comment]
https://github.com/openstax/cnx-automation/pull/213

See comment in the PR about maybe reversing the test case.

**Comment by Dantemss** [comment]
Closing because it was decided we do not need to explicitly test for these.
