### ISSUE TITLE
AAT, I'd like a webview test that asserts This list starts *open* (unlike the TOC) unless the initial page width is < 640 (i.e. mobile)

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#222]
# CASE NUM: C195056
## Section

Show Which Books a Single Page is in

https://trello.com/c/i560M3Af/422-front-end-show-which-books-a-single-page-is-in
Bugs: https://github.com/Connexions/webview/milestone/3

## User story

AAT, I'd like a webview test that asserts This list starts *open* (unlike the TOC) unless the initial page width is < 640 (i.e. mobile)

## Steps

Can use this link to test: https://staging.cnx.org/contents/4fGVMb7P/Taboo-language-and-slanguage

be sure to check the mobile width (< 640 px wide) as well -- that width will have the books list default closed

**Comment by kerwinso** [comment]
@BrianYing found that if the width is exactly 640px, then the books list is open but the contents do not appear. This was already reported in https://github.com/Connexions/webview/issues/1626.

**Comment by m1yag1** [comment]
This is closed by #250
