### ISSUE TITLE
import 4 new webview test cases from TestRail

### ISSUE THREAD

**Issue by kerwinso** [openstax/cnx-automation#290]
[C210285](https://openstax.testrail.com/index.php?/cases/view/210285&group_by=cases:section_id&group_order=asc&group_id=8031) - www should redirect properly: may not be able to automate this one since it's interacting with the browser itself, not a DOM

[C210270](https://openstax.testrail.com/index.php?/cases/view/210270) - Staging book covers should match production

[C210286](https://openstax.testrail.com/index.php?/cases/view/210286) - big tables should be scrollable horizontally using mouse

[C210287](https://openstax.testrail.com/index.php?/cases/view/210287) - fetch exercises by nickname

**Comment by m1yag1** [comment]
Replaced by #319, #318 , #316 , #317 
CC: @kerwinso
