### ISSUE TITLE
create automated test for webview C176263

### ISSUE THREAD

**Issue by kerwinso** [openstax/cnx-automation#291]
Somehow this one got missed:

"Donation form passes values to ebank.rice.edu for processing" (https://openstax.testrail.com/index.php?/cases/view/176263)

**Comment by Dantemss** [comment]
I think we had decided it was out of scope because it's not a site we control, but yeah it could be revisited.

**Comment by kerwinso** [comment]
It's true it's not a site we control, but the test is only to check that the user is sent through to that site -- not to interact with it.

**Comment by m1yag1** [comment]
Closing b/c I re-opened #50
