### ISSUE TITLE
As a tester, I'd like a webview test that asserts Books show part of the introduction

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#38]
1. Go to test environment

2. Scroll down to the books section

**Comment by Dantemss** [comment]
Do we want this test for all books or only some specific books? Not all books in qa.cnx.org display the intro properly in the home page at the moment.

**Comment by Dantemss** [comment]
https://trello.com/c/DL7xEWon/226-book-summaries-inconsistently-populate-to-new-web-view

**Comment by kerwinso** [comment]
Automating this test is (partially) blocked until the above Trello card gets resolved.

**Comment by Dantemss** [comment]
Added a test: https://github.com/openstax/cnx-automation/pull/69

This test will not pass until all books in the home page have titles and intros.

**Comment by Dantemss** [comment]
I changed the test to require that the number of blank intros be 10 or less (which is the current number of blank intros on QA).

So this is no longer blocked.

**Comment by m1yag1** [comment]
Resolved by #69
