### ISSUE TITLE
Jenkins test failing due to container name collision

### ISSUE THREAD

**Issue by pumazi** [openstax/cnx-automation#386]
We're seeing build failures because `cnx-func-testing-1` already exists. This happens when two branches run at the same time. The `BUILD_ID` for those branch jobs is `1`. 

We'll need to change the container name from `cnx-func-testing-${BUILD_ID}` to something more unique.

---

I tried replacing the `BUILD_ID` with `BUILD_TAG` at one point, but it faults on branches that contain a `/`, which at some point is url encoded.

**Comment by m1yag1** [comment]
I think BUILD_NUMBER will work. I'll make a PR.
