### ISSUE TITLE
As a tester, I'd like a webview test that asserts Failed searches return 'No results found.'

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#41]
1. Go to test environment

2. Click on "search" on the top menu.

3. Type random query like "asdfafddafsf" into the search box, and hit return.

**Comment by Dantemss** [comment]
https://github.com/openstax/cnx-automation/pull/67

Let me know if I should test for the Polish message too.

**Comment by m1yag1** [comment]
Completed by #67
