### ISSUE TITLE
As a tester, I'd like a webview test that asserts About Us learn more links work

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#44]
1. Click About Us on the top of the home page and get into About Us' main page

'Learn more about the OpenStax team' goes to https://openstax.org/about

'Learn more about the foundations supporting OpenStax projects like CNX' goes to https://openstax.org/foundation

**Comment by Dantemss** [comment]
https://github.com/openstax/cnx-automation/pull/72
