### ISSUE TITLE
As a tester, I'd like a webview test that asserts E-mail links are clickable

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#47]
1. Click About Us on the top of the home page and get into About Us' main page

2. Click Contact which is on the left 

3. Find the email links and click them

**Comment by Dantemss** [comment]
This should be covered by the test for https://github.com/openstax/cnx-automation/issues/46 (I built the test so selenium matches `a[href="mailto:support@openstax.org"]`). Clicking the link opens the external email client, so I can't easily test that in Selenium.

**Comment by Dantemss** [comment]
https://github.com/openstax/cnx-automation/pull/74
