### ISSUE TITLE
As a tester, I'd like a webview test that asserts Contact displays "Questions" with headings "Technical support" and "General Questions"

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#48]
1. Click About Us on the top of the home page and get into About Us' main page

2. Click Contact which is on the left 

3. check whether Contact displays "Questions" with headings "Technical support" and "General Questions"

**Comment by Dantemss** [comment]
https://github.com/openstax/cnx-automation/pull/74
