### ISSUE TITLE
As a tester, I'd like a webview test that asserts Donation form passes values to ebank.rice.edu for processing

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#50]
1. Open test environment

2. Click on the "Give" link

3. Click on the "Donate Now" button

4. Fill out the Give form

5. Click on the "Continue"

**Comment by Dantemss** [comment]
Should I use any values in particular?
I know the form will allow any value, as it allowed even letters in the zip code (well the email field requires an `@`)
Also not sure I can verify the values on the other side. None of them are visible in the next form.
I could instead check that the form action url matches what we expect ¯\_(ツ)_/¯

**Comment by Dantemss** [comment]
We decided to test the action url has the correct value instead.

**Comment by Dantemss** [comment]
https://github.com/openstax/cnx-automation/pull/76

**Comment by m1yag1** [comment]
Completed by #76

**Comment by m1yag1** [comment]
@kerwinso I reopened this to replace #291

**Comment by Dantemss** [comment]
We do have a test that checks we go to ebank.rice.edu already, but it doesn't check that ebank gets the correct parameter values like the test case wants.

**Comment by Dantemss** [comment]
Ah maybe the test could be improved, it's not too explicit about what it is testing. The url is here instead of being in the test: https://github.com/openstax/cnx-automation/blob/7b7f514efb684534f050b93f1f918a49d79b5360/pages/webview/donate_form.py#L12

**Comment by kerwinso** [comment]
This is a deprecated CNX test since all the donation traffic will go to OSWeb, and should be tested there.
