### ISSUE TITLE
As a tester, I'd like a webview test that asserts Message "please fill out this field" pops up when required fields are blank

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#52]
1. Open test environment

2. Click on the "Give" on the top of the page

3. Click on the "Donate Now" 

4. Click on continue without filling any information 

5. Check whether there is a message saying "please fill out this field" popping up

**Comment by Dantemss** [comment]
https://github.com/openstax/cnx-automation/pull/76
