### ISSUE TITLE
Broken "Run Functional Tests" stage on jenkins

### ISSUE THREAD

**Issue by pumazi** [openstax/cnx-automation#555]
See for example `https://jenkins-dev.cnx.org:8080/blue/organizations/jenkins/openstax%2Fcnx-press/detail/master/46/pipeline`

![Screen Shot 2019-03-15 at 09 59 37](https://user-images.githubusercontent.com/168470/54448591-5b16a800-4709-11e9-8956-5a5af6628cc9.png)

---

I believe this is due to the move away from `tox`

**Comment by m1yag1** [comment]
Yep you can replace tox -- with pytest

**Comment by m1yag1** [comment]
This can be resolve by https://github.com/openstax/pipeline-library/pull/2 cc: @pumazi

**Comment by m1yag1** [comment]
resolved by openstax/pipeline-library#2
