### ISSUE TITLE
As a tester, I'd like a webview test that asserts Clicking the X on a search term or filter value removes that term or filter

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#88]
1. Go to test environment

2. Click on "search" in the head menu bar

3. Type any query into the search textbox

4. Click on any filter option on the left menu

5. Hover over a search term and click "X" on the top left corner of that term
The term is removed and a result list without that filter is returned.

**Comment by Dantemss** [comment]
https://github.com/openstax/cnx-automation/pull/112
