### ISSUE TITLE
As a tester, I'd like a webview test that asserts Advanced Search allows searches on any filter values

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#92]
1. Go to test environment

2. Click on "search" in the head menu bar

3. Click on "advanced search" button 

4. Select a few filters from the drop-down menu (e.g., Subject: Arts, Type: Books, Language: Espanol)

5. Click "submit" 
A List with the filtered result should be displayed.

**Comment by Dantemss** [comment]
https://github.com/openstax/cnx-automation/pull/112
