### ISSUE TITLE
As a tester, I'd like a webview test that asserts Amount bar ranges from 5-10,000 and can be dragged to adjust

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#93]
Open test environment

Click on the "Give" on the top of the page

Click on the "Donate Now" 

Try numbers in the amount bar to see whether it ranges from 5-10,000 and can be dragged to adjust

 Amount bar ranges from 5-10,000 and can be dragged to adjust.

**Comment by Dantemss** [comment]
https://github.com/openstax/cnx-automation/pull/116

The issue says to drag the slider, but using the action chains to drag seemed very flaky (the size of the bar depends on the screen resolution so calculating offsets would be weird). So I used the keyboard arrow keys instead.

**Comment by m1yag1** [comment]
Completed by #116
