### ISSUE TITLE
As a tester, I'd like a webview test that asserts Book title, sources, social media icons, contents button, search, progress bar appears in the grey box below headings

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#96]
1. Go to test environment

2. Click on any book

Check for the following in the grey box below top nav:

-Book title

-Book by: 

-social media icons

-contents button

-search bar 

-progress bar with Back and Next links

**Comment by Dantemss** [comment]
https://github.com/openstax/cnx-automation/pull/114
