### ISSUE TITLE
As a tester, I'd like a webview test that asserts "Get this book" button is interactive

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-automation#98]
1. Go to test environment

2. Click on any books

3. Click on the "get this book" green button
The "get this book" button is interactive.  NOTE: on staging.cnx.org, some of the file downloads may be 0 bytes. This is a known condition and not a bug.

**Comment by Dantemss** [comment]
I don't see this green button. Was it removed? There's a downloads section at the bottom with a green button, but the button simply gives more details about the files available to download (and you don't even have to click it to download the files)

**Comment by m1yag1** [comment]
@kerwinso will know. ☝️

**Comment by Dantemss** [comment]
I suppose I can still make the failing test based on what's on prod.

**Comment by kerwinso** [comment]
Yes @Dantemss , a failing test would actually be helpful. You can look on cnx.org to see how to grab that element.

**Comment by Dantemss** [comment]
https://github.com/openstax/cnx-automation/pull/125

**Comment by Dantemss** [comment]
Made the test look at the button menu, then compare that to the footer and expect them to match. So that means this is no longer blocked.

**Comment by kerwinso** [comment]
Also, discussion of 'is a missing Get This Book button a bug or not?' happening here: https://github.com/Connexions/webview/issues/1659

**Comment by kerwinso** [comment]
Confirmed that the green button does appear if there are downloads available, and will not appear if there are no downloads available.
